### ISSUE TITLE
json/positions.json not found

### ISSUE THREAD

**Issue by rhaamo** [f4iha/aprs-maps#1]
Getting an error about `json/positions.json`, what should go in it ?

```
Traceback (most recent call last):
  File "/home/dashie/aprs-maps/convert.py", line 86, in <module>
    with open(jsonFolder+'positions.json', 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'json/positions.json'
```

**Comment by f4iha** [comment]
@rhaamo this is happening during the first use because the `positions.json` and `relays.json` are not available. I added the piece of code which checks if they are existing and if not, the script is creating the empty json files

**Comment by rhaamo** [comment]
perfect, that fixed it. everything works thanks!
